SectionVerb {
        EnableSequence [
                cset "name='TX0 SEL' IIS0"
                cset "name='RX0 SEL' IIS1"

                cset "name='FE_FAST_PLAYBACK TX Switch' on"
                cset "name='FE_CAPTURE_DSP RX Switch' on"
        ]

        DisableSequence [
                cset "name='FE_CAPTURE_DSP RX Switch' off"
                cset "name='FE_FAST_PLAYBACK TX Switch' off"
        ]
}

SectionDevice."Speaker" {
        Comment "Speaker playback"

        ConflictingDevices [
                "Earpiece"
                "Headphones"
        ]

        EnableSequence [
                cset "name='TX0 MIXER0 Mode' NOT_MIX"
                cset "name='Headphone Playback Switch' on"
                cset "name='Headphone Volume' 11"
        ]

        DisableSequence [
                cset "name='Headphone Volume' 0"
                cset "name='Headphone Playback Switch' off"
        ]

        Value {
                PlaybackPriority 200
                PlaybackChannels 2
                PlaybackPCM "hw:${CardId},0"
        }
}


SectionDevice."Mic" {
        Comment "Microphone capture"

        ConflictingDevices [
                "Headset"
        ]

        EnableSequence [
                cset "name='ADCL Mixer MIC' on"
                cset "name='Capture Volume' 7"
        ]

        DisableSequence [
                cset "name='ADCL Mixer MIC' off"
        ]

        Value {
                CapturePriority 200
        }

        Macro.pcm_split.SplitPCMDevice {
                Name "ums9230_mono_in"
                Device 1
                Direction Capture
                HWChannels 2
                Channels 1
                Channel0 0
                ChannelPos0 MONO
        }
}
